In [5]:
import librosa,librosa.display
import librosa as lr
import numpy as np
import matplotlib.pyplot as plt
from glob import glob
import scipy
from scipy import signal
from scipy.io import wavfile
import soundfile as sf
import os
import wave
import contextlib


def find_mean(y: np.ndarray, fs: int) -> float:
    """
    Compute mean frequency
    :param y: 1-d signal
    :param fs: sampling frequency [Hz]
    :return: mean frequency
    """
    spec = np.abs(np.fft.rfft(y))
    freq = np.fft.rfftfreq(len(y), d=1/fs)
    amp = spec / spec.sum()
    mean = (freq * amp).sum()
    return mean




def do_it(file,new_path,i=1):
    audio_files= glob(file + '/*.wav')
    len(audio_files)
    print(audio_files)
    print("type",audio_files)
    print(len(audio_files))
    for data in range(0,(len(audio_files))):
        # print(audio_files[data])
        file = audio_files[data]
        print("Path",file)
        filename = os.path.basename(file)
        print(filename)
        signal, sr = librosa.load(file, sr=22050)
        print(type(signal))
        print("baba yaga")
        ray = np.array([])
        # print(type(ray))
        # print(len(signal))

        with contextlib.closing(wave.open(file, 'r')) as f:
            frames = f.getnframes()
            rate = f.getframerate()
            duration = frames / float(rate)
            print("Duration", duration)

        for x in signal:
            val = x
            if val < 0.001 and val > -0.001:
                x = 2
            else:
                ray = np.append(ray, x)

        print(len(ray))
        # librosa.display.waveplot(signal, sr=sr)
        # plt.xlabel("Time")
        # plt.ylabel("Amplitude")
        # plt.show()
        #
        # ray = ray
        # librosa.display.waveplot(ray, sr=sr, color='red')
        # plt.xlabel("Time")
        # plt.ylabel("Amplitude")
        # plt.show()
        new_path = "F:/Covid-19 Project/Negative-con-20200508T005007Z-001/Negative-con/"
        scipy.io.wavfile.write(new_path + filename, 22050, ray)
        f = sf.SoundFile(file)
        print('samples = {}'.format(len(f)))
        print('sample rate = {}'.format(f.samplerate))
        print('seconds = {}'.format(len(f) / f.samplerate))
        print("real", len(signal))
        print("cropped", len(ray))
        print("\n")
        new_path = new_path+filename
        f = sf.SoundFile(new_path)
        print('samples = {}'.format(len(f)))
        print('sample rate = {}'.format(f.samplerate))
        print('seconds = {}'.format(len(f) / f.samplerate))

        duration = len(f) / f.samplerate


new_path = "F:/Covid-19 Project/Negative-con-20200508T005007Z-001/Negative-con/Neg"

file ="F:/Covid-19 Project/Negative-con-20200508T005007Z-001/Negative-con/"
#"F:/Covid-19 Project/Negative-con-20200508T005007Z-001/Negative-con/Neg"


do_it(file,new_path)

['F:/Covid-19 Project/Negative-con-20200508T005007Z-001/Negative-con\\neg-11.wav', 'F:/Covid-19 Project/Negative-con-20200508T005007Z-001/Negative-con\\neg-12.wav', 'F:/Covid-19 Project/Negative-con-20200508T005007Z-001/Negative-con\\neg-13.wav', 'F:/Covid-19 Project/Negative-con-20200508T005007Z-001/Negative-con\\neg-15.wav', 'F:/Covid-19 Project/Negative-con-20200508T005007Z-001/Negative-con\\neg-16.wav', 'F:/Covid-19 Project/Negative-con-20200508T005007Z-001/Negative-con\\neg-17.wav', 'F:/Covid-19 Project/Negative-con-20200508T005007Z-001/Negative-con\\neg-18.wav', 'F:/Covid-19 Project/Negative-con-20200508T005007Z-001/Negative-con\\neg-2.wav', 'F:/Covid-19 Project/Negative-con-20200508T005007Z-001/Negative-con\\neg-21.wav', 'F:/Covid-19 Project/Negative-con-20200508T005007Z-001/Negative-con\\neg-22.wav', 'F:/Covid-19 Project/Negative-con-20200508T005007Z-001/Negative-con\\neg-25.wav', 'F:/Covid-19 Project/Negative-con-20200508T005007Z-001/Negative-con\\neg-26.wav', 'F:/Covid-19 Pro

<class 'numpy.ndarray'>
baba yaga
Duration 10.0
124440
samples = 124440
sample rate = 22050
seconds = 5.643537414965986
real 220500
cropped 124440


samples = 124440
sample rate = 22050
seconds = 5.643537414965986
Path F:/Covid-19 Project/Negative-con-20200508T005007Z-001/Negative-con\neg-22.wav
neg-22.wav
<class 'numpy.ndarray'>
baba yaga
Duration 10.0
153222
samples = 153222
sample rate = 22050
seconds = 6.948843537414966
real 220500
cropped 153222


samples = 153222
sample rate = 22050
seconds = 6.948843537414966
Path F:/Covid-19 Project/Negative-con-20200508T005007Z-001/Negative-con\neg-25.wav
neg-25.wav
<class 'numpy.ndarray'>
baba yaga
Duration 10.0
102012
samples = 102012
sample rate = 22050
seconds = 4.626394557823129
real 220500
cropped 102012


samples = 102012
sample rate = 22050
seconds = 4.626394557823129
Path F:/Covid-19 Project/Negative-con-20200508T005007Z-001/Negative-con\neg-26.wav
neg-26.wav
<class 'numpy.ndarray'>
baba yaga
Duration 10.0
164636
samples = 164636
samp

# Image Subtraction

In [1]:
import cv2 as cv
import cv2
import numpy as np
cap= cv.VideoCapture('F:/C_new.wmv')
backSub = cv.bgsegm.createBackgroundSubtractorMOG()
#backSub = cv.bgsegm.createBackgroundSubtractorGMG()
#backSub = cv.createBackgroundSubtractorMOG2()
#backSub = cv.createBackgroundSubtractorKNN()
while True:
    ret, frame = cap.read()
    if frame is None:
        break
    b_frame=cv2.GaussianBlur(frame,(5,5),0)
    fgMask = backSub.apply(b_frame)
    contours,hierachy=cv2.findContours(fgMask,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
    for cnt in contours:
        area=cv2.contourArea(cnt)
        if area > 1000:
            rect=cv2.minAreaRect(cnt)
            #print(area)
            box=cv2.boxPoints(rect)
            print(box)
            #print(rect)
            box=np.int0(box)
            #print(box)
            cv2.drawContours(frame,[box],-1,(0,255,0),3)
        
    
            
    cv2.circle(frame, (495,360), 9, (255,0,255), -1)
    #cv.rectangle(fgMask, (10, 2), (100,20), (255,255,255), -1)
    

    cv.imshow('Frame', frame)
    cv.imshow('FG Mask', fgMask)
    
    keyboard = cv.waitKey(30)

    if keyboard == 'q' or keyboard == 27:
        break
cap.release()
cv2.destroyAllWindows()

[[509.3447   349.21857 ]
 [482.86887  330.4068  ]
 [635.50024  115.592285]
 [661.9761   134.40405 ]]
[[509.3447   349.21857 ]
 [482.86887  330.4068  ]
 [635.50024  115.592285]
 [661.9761   134.40405 ]]
[[509.3447   349.21857 ]
 [482.86887  330.4068  ]
 [635.50024  115.592285]
 [661.9761   134.40405 ]]
[[509.04736 348.94766]
 [499.0973  339.94516]
 [675.42773 145.05365]
 [685.3778  154.05615]]
[[509.04736 348.94766]
 [499.0973  339.94516]
 [675.42773 145.05365]
 [685.3778  154.05615]]
[[509.04736 348.94766]
 [499.0973  339.94516]
 [675.42773 145.05365]
 [685.3778  154.05615]]
[[509.04736 348.94766]
 [499.0973  339.94516]
 [675.42773 145.05365]
 [685.3778  154.05615]]
[[509.04736 348.94766]
 [499.0973  339.94516]
 [675.42773 145.05365]
 [685.3778  154.05615]]
[[509.04736 348.94766]
 [499.0973  339.94516]
 [675.42773 145.05365]
 [685.3778  154.05615]]
[[509.01233 348.9174 ]
 [499.07776 339.91418]
 [675.5657  145.16891]
 [685.50024 154.17212]]
[[509.01233 348.9174 ]
 [499.07776 339.91418]


# Second Approach

In [9]:
import cv2 as cv
import cv2
import numpy as np

cap = cv.VideoCapture('F:/C_new.wmv')
backSub = cv.bgsegm.createBackgroundSubtractorMOG()
#backSub = cv.bgsegm.createBackgroundSubtractorGMG()
#backSub = cv.createBackgroundSubtractorMOG2()
#backSub = cv.createBackgroundSubtractorKNN()
while True:
    ret, frame = cap.read()
    if frame is None:
        break
    hsv=cv2.cvtColor(frame,cv2.COLOR_BGR2HSV)
    l_red=np.array([170,50,50])
    U_red=np.array([180,255,255])
    Mask=cv2.inRange(hsv,l_red,U_red)
    #fgMask = backSub.apply(frame)
    contours,hierachy=cv2.findContours(Mask,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
    a=cv2.drawContours(frame,contours,-1,(0,255,0),3)
    print(a)
    cv2.circle(frame, (630,345), 9, (255,0,0), -1)
    
    
    #cv.rectangle(fgMask, (10, 2), (100,20), (255,255,255), -1)
    

    cv.imshow('Frame', frame)
    cv.imshow('FG Mask', Mask)
    
    keyboard = cv.waitKey(30)
    if keyboard == 'q' or keyboard == 27:
        break
cap.release()
cv2.destroyAllWindows()

[[[156 156 156]
  [156 156 156]
  [156 156 156]
  ...
  [145 145 145]
  [145 145 145]
  [145 145 145]]

 [[157 157 157]
  [157 157 157]
  [157 157 157]
  ...
  [146 146 146]
  [146 146 146]
  [146 146 146]]

 [[158 158 158]
  [158 158 158]
  [158 158 158]
  ...
  [147 147 147]
  [147 147 147]
  [147 147 147]]

 ...

 [[133 133 255]
  [133 133 255]
  [133 133 255]
  ...
  [159 159 159]
  [159 159 159]
  [159 159 159]]

 [[181 172 169]
  [181 172 169]
  [181 172 169]
  ...
  [158 158 158]
  [158 158 158]
  [158 158 158]]

 [[180 171 168]
  [180 171 168]
  [180 171 168]
  ...
  [159 159 159]
  [159 159 159]
  [159 159 159]]]
[[[156 156 156]
  [156 156 156]
  [156 156 156]
  ...
  [145 145 145]
  [145 145 145]
  [145 145 145]]

 [[157 157 157]
  [157 157 157]
  [157 157 157]
  ...
  [146 146 146]
  [146 146 146]
  [146 146 146]]

 [[158 158 158]
  [158 158 158]
  [158 158 158]
  ...
  [147 147 147]
  [147 147 147]
  [147 147 147]]

 ...

 [[133 133 255]
  [133 133 255]
  [133 133 255]
  ..

[[[156 156 156]
  [156 156 156]
  [156 156 156]
  ...
  [144 144 144]
  [144 144 144]
  [144 144 144]]

 [[157 157 157]
  [157 157 157]
  [157 157 157]
  ...
  [145 145 145]
  [145 145 145]
  [145 145 145]]

 [[158 158 158]
  [158 158 158]
  [158 158 158]
  ...
  [147 147 147]
  [147 147 147]
  [147 147 147]]

 ...

 [[133 133 255]
  [133 133 255]
  [133 133 255]
  ...
  [159 159 159]
  [159 159 159]
  [159 159 159]]

 [[181 172 169]
  [181 172 169]
  [181 172 169]
  ...
  [158 158 158]
  [158 158 158]
  [158 158 158]]

 [[180 171 168]
  [180 171 168]
  [180 171 168]
  ...
  [159 159 159]
  [159 159 159]
  [159 159 159]]]
[[[156 156 156]
  [156 156 156]
  [156 156 156]
  ...
  [144 144 144]
  [144 144 144]
  [144 144 144]]

 [[157 157 157]
  [157 157 157]
  [157 157 157]
  ...
  [145 145 145]
  [145 145 145]
  [145 145 145]]

 [[158 158 158]
  [158 158 158]
  [158 158 158]
  ...
  [147 147 147]
  [147 147 147]
  [147 147 147]]

 ...

 [[133 133 255]
  [133 133 255]
  [133 133 255]
  ..

[[[156 156 156]
  [156 156 156]
  [156 156 156]
  ...
  [145 145 145]
  [145 145 145]
  [145 145 145]]

 [[157 157 157]
  [157 157 157]
  [157 157 157]
  ...
  [146 146 146]
  [146 146 146]
  [146 146 146]]

 [[158 158 158]
  [158 158 158]
  [158 158 158]
  ...
  [147 147 147]
  [147 147 147]
  [147 147 147]]

 ...

 [[133 133 255]
  [133 133 255]
  [133 133 255]
  ...
  [159 159 159]
  [159 159 159]
  [159 159 159]]

 [[181 172 169]
  [181 172 169]
  [181 172 169]
  ...
  [158 158 158]
  [158 158 158]
  [158 158 158]]

 [[180 171 168]
  [180 171 168]
  [180 171 168]
  ...
  [159 159 159]
  [159 159 159]
  [159 159 159]]]
[[[156 156 156]
  [156 156 156]
  [156 156 156]
  ...
  [145 145 145]
  [145 145 145]
  [145 145 145]]

 [[157 157 157]
  [157 157 157]
  [157 157 157]
  ...
  [146 146 146]
  [146 146 146]
  [146 146 146]]

 [[158 158 158]
  [158 158 158]
  [158 158 158]
  ...
  [147 147 147]
  [147 147 147]
  [147 147 147]]

 ...

 [[133 133 255]
  [133 133 255]
  [133 133 255]
  ..

[[[156 156 156]
  [156 156 156]
  [156 156 156]
  ...
  [144 144 144]
  [144 144 144]
  [144 144 144]]

 [[157 157 157]
  [157 157 157]
  [157 157 157]
  ...
  [145 145 145]
  [145 145 145]
  [145 145 145]]

 [[158 158 158]
  [158 158 158]
  [158 158 158]
  ...
  [147 147 147]
  [147 147 147]
  [147 147 147]]

 ...

 [[  6   5 229]
  [  6   5 229]
  [  6   5 229]
  ...
  [209 209 209]
  [209 209 209]
  [209 209 209]]

 [[159 158 193]
  [159 158 193]
  [159 158 193]
  ...
  [159 159 159]
  [159 159 159]
  [159 159 159]]

 [[162 161 196]
  [162 161 196]
  [162 161 196]
  ...
  [158 158 158]
  [158 158 158]
  [158 158 158]]]
[[[156 156 156]
  [156 156 156]
  [156 156 156]
  ...
  [144 144 144]
  [144 144 144]
  [144 144 144]]

 [[157 157 157]
  [157 157 157]
  [157 157 157]
  ...
  [145 145 145]
  [145 145 145]
  [145 145 145]]

 [[158 158 158]
  [158 158 158]
  [158 158 158]
  ...
  [147 147 147]
  [147 147 147]
  [147 147 147]]

 ...

 [[  6   5 229]
  [  6   5 229]
  [  6   5 229]
  ..

[[[156 156 156]
  [156 156 156]
  [156 156 156]
  ...
  [147 147 147]
  [147 147 147]
  [147 147 147]]

 [[157 157 157]
  [157 157 157]
  [157 157 157]
  ...
  [147 147 147]
  [147 147 147]
  [147 147 147]]

 [[158 158 158]
  [158 158 158]
  [158 158 158]
  ...
  [149 149 149]
  [149 149 149]
  [149 149 149]]

 ...

 [[  0   0 252]
  [  0   0 252]
  [  0   0 252]
  ...
  [206 209 209]
  [206 209 209]
  [206 209 209]]

 [[  1   1 249]
  [  1   1 249]
  [  1   1 249]
  ...
  [205 208 208]
  [205 208 208]
  [205 208 208]]

 [[  3   3 251]
  [  3   3 251]
  [  3   3 251]
  ...
  [204 207 207]
  [204 207 207]
  [204 207 207]]]
[[[156 156 156]
  [156 156 156]
  [156 156 156]
  ...
  [147 147 147]
  [147 147 147]
  [147 147 147]]

 [[157 157 157]
  [157 157 157]
  [157 157 157]
  ...
  [147 147 147]
  [147 147 147]
  [147 147 147]]

 [[158 158 158]
  [158 158 158]
  [158 158 158]
  ...
  [149 149 149]
  [149 149 149]
  [149 149 149]]

 ...

 [[  0   0 252]
  [  0   0 252]
  [  0   0 252]
  ..

[[[156 156 156]
  [156 156 156]
  [156 156 156]
  ...
  [145 145 145]
  [145 145 145]
  [145 145 145]]

 [[157 157 157]
  [157 157 157]
  [157 157 157]
  ...
  [146 146 146]
  [146 146 146]
  [146 146 146]]

 [[158 158 158]
  [158 158 158]
  [158 158 158]
  ...
  [147 147 147]
  [147 147 147]
  [147 147 147]]

 ...

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [209 209 209]
  [209 209 209]
  [209 209 209]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [160 160 160]
  [160 160 160]
  [160 160 160]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [160 160 160]
  [160 160 160]
  [160 160 160]]]
[[[156 156 156]
  [156 156 156]
  [156 156 156]
  ...
  [145 145 145]
  [145 145 145]
  [145 145 145]]

 [[157 157 157]
  [157 157 157]
  [157 157 157]
  ...
  [146 146 146]
  [146 146 146]
  [146 146 146]]

 [[158 158 158]
  [158 158 158]
  [158 158 158]
  ...
  [147 147 147]
  [147 147 147]
  [147 147 147]]

 ...

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ..

[[[154 154 154]
  [154 154 154]
  [154 154 154]
  ...
  [145 145 145]
  [145 145 145]
  [145 145 145]]

 [[156 156 156]
  [156 156 156]
  [156 156 156]
  ...
  [146 146 146]
  [146 146 146]
  [146 146 146]]

 [[157 157 157]
  [157 157 157]
  [157 157 157]
  ...
  [147 147 147]
  [147 147 147]
  [147 147 147]]

 ...

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [209 209 209]
  [209 209 209]
  [209 209 209]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [160 160 160]
  [160 160 160]
  [160 160 160]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [160 160 160]
  [160 160 160]
  [160 160 160]]]
[[[154 154 154]
  [154 154 154]
  [154 154 154]
  ...
  [145 145 145]
  [145 145 145]
  [145 145 145]]

 [[156 156 156]
  [156 156 156]
  [156 156 156]
  ...
  [146 146 146]
  [146 146 146]
  [146 146 146]]

 [[157 157 157]
  [157 157 157]
  [157 157 157]
  ...
  [147 147 147]
  [147 147 147]
  [147 147 147]]

 ...

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ..

In [ ]:
def get_center(contour):
    M = cv2.moments(contour)
    cX = int(M["m10"] / M["m00"])
    cY = int(M["m01"] / M["m00"])

    return cX, cY


def get_angle(p1, p2):
    return math.atan2(p1[1] - p2[1], p1[0] - p2[0]) * 180/math.pi

In [2]:
import cv2 as cv
import math
import cv2
import numpy as np
cap= cv.VideoCapture('F:/C_new.wmv')
backSub = cv.bgsegm.createBackgroundSubtractorMOG()
#backSub = cv.bgsegm.createBackgroundSubtractorGMG()
#backSub = cv.createBackgroundSubtractorMOG2()
#backSub = cv.createBackgroundSubtractorKNN()
while True:
    ret, frame = cap.read()
    if frame is None:
        break
    b_frame=cv2.GaussianBlur(frame,(5,5),0)
    fgMask = backSub.apply(b_frame)
    contours,hierachy=cv2.findContours(fgMask,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
    for cnt in contours:
        area=cv2.contourArea(cnt)
        if area > 1000:
            rect=cv2.minAreaRect(cnt)
            M = cv2.moments(cnt)
            cX = int(M["m10"] / M["m00"])
            cY = int(M["m01"] / M["m00"])
            cv2.circle(frame, (cX,cY), 9, (255,0,255), -1)
            diffx=cX-495
            diffy=cY-360
            per=math.atan2(diffy,diffx)
            print(per)
            p=math.degrees(per)
            box=cv2.boxPoints(rect)
            box=np.int0(box)
            cv2.putText(frame,str(int(p)),(75,45),cv2.FONT_HERSHEY_COMPLEX,0.7,(255,0,255),2)
            cv2.drawContours(frame,[box],-1,(0,255,0),3)
        
    
            
    cv2.circle(frame, (495,360), 9, (255,0,255), -1)
    #cv.rectangle(fgMask, (10, 2), (100,20), (255,255,255), -1)
    

    cv.imshow('Frame', frame)
    cv.imshow('FG Mask', fgMask)
    
    keyboard = cv.waitKey(30)

    if keyboard == 'q' or keyboard == 27:
        break
cap.release()
cv2.destroyAllWindows()

-0.9982067608042247
-0.9982067608042247
-0.9982067608042247
-0.844153986113171
-0.844153986113171
-0.844153986113171
-0.844153986113171
-0.844153986113171
-0.844153986113171
-0.844153986113171
-0.844153986113171
-0.844153986113171
-0.844153986113171
-0.844153986113171
-0.844153986113171
-0.844153986113171
-0.844153986113171
-0.844153986113171
-0.7395587375163315
-0.7395587375163315
-0.7395587375163315
-0.7395587375163315
-0.7395587375163315
-0.7395587375163315
-0.7347502711173363
-0.7347502711173363
-0.7347502711173363
-0.7347502711173363
-0.7395587375163315
-0.7395587375163315
-0.7395587375163315
-0.7395587375163315
-0.7395587375163315
-0.7395587375163315
-0.7395587375163315
-0.7395587375163315
-0.7395587375163315
-0.7395587375163315
-0.7395587375163315
-0.7395587375163315
-0.7395587375163315
-0.7395587375163315
-0.6350267353903137
-0.6350267353903137
-0.635315752723307
-0.635315752723307
-0.635315752723307
-0.635315752723307
-0.635315752723307
-0.635315752723307
-0.635315752723307
-0