# WEEK 1


In [11]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer

In [12]:
sentences=['I love my cat','i love my dog']
token=Tokenizer(num_words=100)#The Tokenizer will take 100 most common words inorder to assign no to them 
token.fit_on_texts(sentences)#this 'fit_on_texts' will assign no to them
word_index=token.word_index #after assiging them values this method will make a dictionary like  
                            # this '{'i': 1, 'love': 2, 'my': 3, 'cat': 4, 'dog': 5}'

    
    
print(word_index)
#Tokenizer will strips punctuation ,like if we define I or i it will assign same value to it, 

{'i': 1, 'love': 2, 'my': 3, 'cat': 4, 'dog': 5}


In [4]:
sentences=['I love my cat','i love my dog','You love my cat!']
#Tokenizer will strips punctuation out ,if we have 'cat!' it will treat it as cat
token=Tokenizer(num_words=100)
token.fit_on_texts(sentences)
word=token.word_index
print(word)

{'love': 1, 'my': 2, 'i': 3, 'cat': 4, 'dog': 5, 'you': 6}


In [12]:
sentences=['I love my cat','i love my dog','You love my cat!']
#Tokenizer will strips punctuation out ,if we have 'cat!' it will treat it as cat
token=Tokenizer(num_words=100)
token.fit_on_texts(sentences)

word=token.word_index

texts=token.texts_to_sequences(sentences)#this will make a sequence of our list of sentences like this '
                                         #[[3, 1, 2, 4], [3, 1, 2, 5], [6, 1, 2, 4]]  [3,1,2,4]=I love my cat'
print(word)
print(texts)

{'love': 1, 'my': 2, 'i': 3, 'cat': 4, 'dog': 5, 'you': 6}
[[3, 1, 2, 4], [3, 1, 2, 5], [6, 1, 2, 4]]


In [5]:
sentences=['I really love my cat','i love my dog','You love him']
texts=token.texts_to_sequences(sentences)
print(texts)
word=token.word_index
print(word)


#If we look it up we saw that we have '[7,1]=You Love' but we want 'You Love him'.
#We learn from this that we need to have a large data to build up a good vocabulary


[[3, 1, 2, 4], [3, 1, 2, 5], [6, 1]]
{'love': 1, 'my': 2, 'i': 3, 'cat': 4, 'dog': 5, 'you': 6}


In [6]:



#TRAINING DATA
sentences=['I love my cat','i love my dog','You love my cat!']
token=Tokenizer(num_words=100 ,oov_token='<OOV>')#OOV=Out Of Vocabulary
#we add one thing to the tokenizer which is 'oov_token='<OOV> it give <OOV> to any value to the word which is out of vocabulary
token.fit_on_texts(sentences)
word=token.word_index
print(sentences)
print(word)
texts=token.texts_to_sequences(sentences)
print (texts)

#TESTING DATA

sent=['I love my LORD','He accept my love ']
test_text=token.texts_to_sequences(sent)
print(sent)
print(test_text)


['I love my cat', 'i love my dog', 'You love my cat!']
{'<OOV>': 1, 'love': 2, 'my': 3, 'i': 4, 'cat': 5, 'dog': 6, 'you': 7}
[[4, 2, 3, 5], [4, 2, 3, 6], [7, 2, 3, 5]]
['I love my LORD', 'He accept my love ']
[[4, 2, 3, 1], [1, 1, 3, 2]]


# PADDING


In [32]:
#Padiing help us to unifron our data just like we did in building neural network when we make all our pics the same size

In [31]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [36]:
sentences=['I love my cat','i love my dog','You love my cat!','Your are getting paid for this job']
token=Tokenizer(num_words=100 ,oov_token='<OOV>')
token.fit_on_texts(sentences)
word=token.word_index
print(sentences)
texts=token.texts_to_sequences(sentences)
pad_seq=pad_sequences(texts)
print (texts)

print("+++++++++++")
print(pad_seq)


['I love my cat', 'i love my dog', 'You love my cat!', 'Your are getting paid for this job']
[[4, 2, 3, 5], [4, 2, 3, 6], [7, 2, 3, 5], [8, 9, 10, 11, 12, 13, 14]]
+++++++++++
[[ 0  0  0  4  2  3  5]
 [ 0  0  0  4  2  3  6]
 [ 0  0  0  7  2  3  5]
 [ 8  9 10 11 12 13 14]]


In [43]:
#as we saw data has been padded , if we want "0" after we just need to do
pad_seq=pad_sequences(texts,padding='post')
#we can also specify the length of a sentences like this
pa_seq=pad_sequences(texts,padding='post',maxlen=3)
print(pad_seq)
print("++++++++")
print(pa_seq)
#here you can see we lose info , if we want it to remove info at the end we just do
pa=pad_sequences(texts,padding='post',maxlen=3,truncating='post')
print("++++++++")
print(pa)


[[ 4  2  3  5  0  0  0]
 [ 4  2  3  6  0  0  0]
 [ 7  2  3  5  0  0  0]
 [ 8  9 10 11 12 13 14]]
++++++++
[[ 2  3  5]
 [ 2  3  6]
 [ 2  3  5]
 [12 13 14]]
++++++++
[[ 4  2  3]
 [ 4  2  3]
 [ 7  2  3]
 [ 8  9 10]]


# WEEK 2


In [7]:
import tensorflow as tf
print(tf.__version__)

2.0.0


In [3]:
tf.enable_eager_execution()#for tensforflow version 1.x we need this line of code to for execution in version 2.x we dont need any thing

In [9]:
import tensorflow_datasets as tfds

In [10]:
imdb, info = tfds.load("imdb_reviews", with_info=True, as_supervised=True)

AttributeError: module 'tensorflow_datasets' has no attribute 'load'

In [5]:
data="My . name . is . Tauqeer"
a=data.lower().split(".")
a

['my ', ' name ', ' is ', ' tauqeer']