In [18]:
import cv2 
import pytesseract

img = cv2.imread('F:/Taknify/C.jpg')

pytesseract.pytesseract.tesseract_cmd=r'F:/Program Files/Tesseract-OCR/tesseract.exe'

# Adding custom options
#custom_config = r'--oem 1 --psm 10'
custom_config= ("_char_whitelist=0123456789 --oem 1 --psm 10 outputbase digits ")
a=cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
#custom_config = r'--oem 1 --psm 10 outputbase digits'
#custom_config =r'0123456789'
b= cv2.bilateralFilter(img, 15, 75, 75) 
print(pytesseract.image_to_string(b, config=custom_config))
cv2.imshow('img', img)
cv2.waitKey(0)

 

[[[39 83  6]
  [39 83  6]
  [39 83  6]
  ...
  [45 91 12]
  [45 91 12]
  [45 91 12]]

 [[39 83  6]
  [39 83  6]
  [39 83  6]
  ...
  [45 91 12]
  [45 91 12]
  [45 91 12]]

 [[39 83  6]
  [39 83  6]
  [39 83  6]
  ...
  [45 91 12]
  [45 91 12]
  [45 91 12]]

 ...

 [[48 89 22]
  [48 89 22]
  [48 89 22]
  ...
  [50 95 16]
  [50 95 16]
  [50 95 16]]

 [[48 88 22]
  [48 88 22]
  [48 88 22]
  ...
  [49 94 15]
  [49 94 15]
  [49 94 15]]

 [[47 88 21]
  [47 88 21]
  [47 88 21]
  ...
  [49 94 15]
  [49 94 15]
  [49 94 15]]]


In [2]:
import cv2
import numpy as np

img = cv2.imread('F:/Taknify/ckt2.png')

# get grayscale image
def get_grayscale(image):
    a=cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    
    return pytesseract.image_to_string(a, config=custom_config)

# noise removal
def remove_noise(image):
    a = cv2.medianBlur(image,5)
    custom_config = r'--oem 3 --psm 6 outputbase digits'
    return pytesseract.image_to_string(a, config=custom_config)
 
#thresholding
def thresholding(image):
    a= cv2.threshold(image, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)[1]
    custom_config = r'--oem 3 --psm 6 outputbase digits'
    pytesseract.image_to_string(a, config=custom_config)
    
    
    

#dilation
def dilate(image):
    kernel = np.ones((5,5),np.uint8)
    return cv2.dilate(image, kernel, iterations = 1)
    
#erosion
def erode(image):
    kernel = np.ones((5,5),np.uint8)
    return cv2.erode(image, kernel, iterations = 1)

#opening - erosion followed by dilation
def opening(image):
    kernel = np.ones((5,5),np.uint8)
    return cv2.morphologyEx(image, cv2.MORPH_OPEN, kernel)

#canny edge detection
def canny(image):
    a= cv2.Canny(image, 100, 200)
    custom_config = r'--oem 3 --psm 6 outputbase digits'
    print(pytesseract.image_to_string(a, config=custom_config))

#skew correction
def deskew(image):
    coords = np.column_stack(np.where(image > 0))
    angle = cv2.minAreaRect(coords)[-1]
    if angle < -45:
        angle = -(90 + angle)
    else:
        angle = -angle
    (h, w) = image.shape[:2]
    center = (w // 2, h // 2)
    M = cv2.getRotationMatrix2D(center, angle, 1.0)
    rotated = cv2.warpAffine(image, M, (w, h), flags=cv2.INTER_CUBIC, borderMode=cv2.BORDER_REPLICATE)
    return rotated

#template matching
def match_template(image, template):
    return cv2.matchTemplate(image, template, cv2.TM_CCOEFF_NORMED) 

In [21]:
canny(img)

. - 3
-

7.7

28 .



In [8]:
#a= cv2.Canny(img, 100, 200)
a=cv2.matchTemplate(img, template, cv2.TM_CCOEFF_NORMED) 


NameError: name 'template' is not defined

In [7]:
import cv2
cv2.imshow('a',a)
cv2.waitKey(5000)
cv2.destroyAllWindows()

In [34]:
a=[1002,1223,4321,4532]
#lol = [[1,2,3],[4,40],[10,20,30]]
for i in a:
    p=int(input("Enter a number"))
    if i==p:
        print('Yes')
    else:
        print("No")

Enter a number1002
Yes
Enter a number1231
No
Enter a number1002
No
Enter a number45321
No


In [28]:
a=[1002,1223,4321,4532]
1002 in a

True

In [27]:
1002==1002

True

In [19]:
import cv2
import pytesseract

img = cv2.imread('F:/Taknify/C.jpg')

h, w, c = img.shape
boxes = pytesseract.image_to_boxes(img) 
for b in boxes.splitlines():
    b = b.split(' ')
    img = cv2.rectangle(img, (int(b[1]), h - int(b[2])), (int(b[3]), h - int(b[4])), (0, 255, 0), 2)

cv2.imshow('img', img)
cv2.waitKey(0)

-1

In [1]:
def text_detector(image):
	orig = image
	(H, W) = image.shape[:2]

	(newW, newH) = (320, 320)
	rW = W / float(newW)
	rH = H / float(newH)

	image = cv2.resize(image, (newW, newH))
	(H, W) = image.shape[:2]

	layerNames = [
		"feature_fusion/Conv_7/Sigmoid",
		"feature_fusion/concat_3"]


	blob = cv2.dnn.blobFromImage(image, 1.0, (W, H),
		(123.68, 116.78, 103.94), swapRB=True, crop=False)

	net.setInput(blob)
	(scores, geometry) = net.forward(layerNames)

	(numRows, numCols) = scores.shape[2:4]
	rects = []
	confidences = []

	for y in range(0, numRows):

		scoresData = scores[0, 0, y]
		xData0 = geometry[0, 0, y]
		xData1 = geometry[0, 1, y]
		xData2 = geometry[0, 2, y]
		xData3 = geometry[0, 3, y]
		anglesData = geometry[0, 4, y]

		# loop over the number of columns
		for x in range(0, numCols):
			# if our score does not have sufficient probability, ignore it
			if scoresData[x] < 0.5:
				continue

			# compute the offset factor as our resulting feature maps will
			# be 4x smaller than the input image
			(offsetX, offsetY) = (x * 4.0, y * 4.0)

			# extract the rotation angle for the prediction and then
			# compute the sin and cosine
			angle = anglesData[x]
			cos = np.cos(angle)
			sin = np.sin(angle)

			# use the geometry volume to derive the width and height of
			# the bounding box
			h = xData0[x] + xData2[x]
			w = xData1[x] + xData3[x]

			# compute both the starting and ending (x, y)-coordinates for
			# the text prediction bounding box
			endX = int(offsetX + (cos * xData1[x]) + (sin * xData2[x]))
			endY = int(offsetY - (sin * xData1[x]) + (cos * xData2[x]))
			startX = int(endX - w)
			startY = int(endY - h)

			# add the bounding box coordinates and probability score to
			# our respective lists
			rects.append((startX, startY, endX, endY))
			confidences.append(scoresData[x])

	boxes = non_max_suppression(np.array(rects), probs=confidences)

	for (startX, startY, endX, endY) in boxes:

		startX = int(startX * rW)
		startY = int(startY * rH)
		endX = int(endX * rW)
		endY = int(endY * rH)
		boundary = 2

		text = orig[startY-boundary:endY+boundary, startX - boundary:endX + boundary]
		text = cv2.cvtColor(text.astype(np.uint8), cv2.COLOR_BGR2GRAY)
		textRecongized = pytesseract.image_to_string(text)
		cv2.rectangle(orig, (startX, startY), (endX, endY), (0, 255, 0), 3)
		orig = cv2.putText(orig, textRecongized, (endX,endY+5), cv2.FONT_HERSHEY_SIMPLEX, 1, (0,0,255), 2, cv2.LINE_AA) 
	return orig


In [2]:
from imutils.object_detection import non_max_suppression
import numpy as np
import time
import cv2
import pytesseract

net = cv2.dnn.readNet("C:/Users/KHAN/frozen_east_text_detection.pb")

In [3]:
def text_detector(image):
	orig = image
	(H, W) = image.shape[:2]

	(newW, newH) = (320, 320)
	rW = W / float(newW)
	rH = H / float(newH)

	image = cv2.resize(image, (newW, newH))
	(H, W) = image.shape[:2]

	layerNames = [
		"feature_fusion/Conv_7/Sigmoid",
		"feature_fusion/concat_3"]


	blob = cv2.dnn.blobFromImage(image, 1.0, (W, H),
		(123.68, 116.78, 103.94), swapRB=True, crop=False)

	net.setInput(blob)
	(scores, geometry) = net.forward(layerNames)

	(numRows, numCols) = scores.shape[2:4]
	rects = []
	confidences = []

	for y in range(0, numRows):

		scoresData = scores[0, 0, y]
		xData0 = geometry[0, 0, y]
		xData1 = geometry[0, 1, y]
		xData2 = geometry[0, 2, y]
		xData3 = geometry[0, 3, y]
		anglesData = geometry[0, 4, y]

		# loop over the number of columns
		for x in range(0, numCols):
			# if our score does not have sufficient probability, ignore it
			if scoresData[x] < 0.5:
				continue

			# compute the offset factor as our resulting feature maps will
			# be 4x smaller than the input image
			(offsetX, offsetY) = (x * 4.0, y * 4.0)

			# extract the rotation angle for the prediction and then
			# compute the sin and cosine
			angle = anglesData[x]
			cos = np.cos(angle)
			sin = np.sin(angle)

			# use the geometry volume to derive the width and height of
			# the bounding box
			h = xData0[x] + xData2[x]
			w = xData1[x] + xData3[x]

			# compute both the starting and ending (x, y)-coordinates for
			# the text prediction bounding box
			endX = int(offsetX + (cos * xData1[x]) + (sin * xData2[x]))
			endY = int(offsetY - (sin * xData1[x]) + (cos * xData2[x]))
			startX = int(endX - w)
			startY = int(endY - h)
            
			# add the bounding box coordinates and probability score to
			# our respective lists
			rects.append((startX, startY, endX, endY))
			confidences.append(scoresData[x])
            
	boxes = non_max_suppression(np.array(rects), probs=confidences)
        
	for (startX, startY, endX, endY) in boxes:

		startX = int(startX * rW)
		startY = int(startY * rH)
		endX = int(endX * rW)
		endY = int(endY * rH)
		boundary = 2

		text = orig[startY-boundary:endY+boundary, startX - boundary:endX + boundary]
		text = cv2.cvtColor(text.astype(np.uint8), cv2.COLOR_BGR2GRAY)
		textRecongized = pytesseract.image_to_string(text)
		cv2.rectangle(orig, (startX, startY), (endX, endY), (0, 255, 0), 3)
		orig = cv2.putText(orig, textRecongized, (endX,endY+5), cv2.FONT_HERSHEY_SIMPLEX, 1, (0,0,255), 2, cv2.LINE_AA) 
	return orig


In [17]:
from imutils.object_detection import non_max_suppression
import numpy as np
import time
import cv2
import pytesseract
pytesseract.pytesseract.tesseract_cmd=r'F:/Program Files/Tesseract-OCR/tesseract.exe'

net = cv2.dnn.readNet("C:/Users/KHAN/frozen_east_text_detection.pb")
#image0 = cv2.imread('F:/2.png')
image1 = cv2.imread('F:/aaddaa.jpg')
#image2 = cv2.imread('image2.jpg')
#image3 = cv2.imread('image3.jpg')
#image4 = cv2.imread('image4.jpg')
array = [image1]
for i in range(0,2):
	for img in array:
		imageO = cv2.resize(img, (640,320), interpolation = cv2.INTER_AREA)
		orig = cv2.resize(img, (640,320), interpolation = cv2.INTER_AREA)
		textDetected = text_detector(image1)
		cv2.imshow("Orig Image",orig)
		cv2.imshow("Text Detection", textDetected)
		time.sleep(2)
		k = cv2.waitKey(700)
		if k == 27:
			break
cv2.destroyAllWindows()

In [23]:
from imutils.object_detection import non_max_suppression
import numpy as np
import time
import cv2
import pytesseract
pytesseract.pytesseract.tesseract_cmd=r'F:/Program Files/Tesseract-OCR/tesseract.exe'

image = cv2.imread('F:/aaddaa.jpg')

blob = cv2.dnn.blobFromImage(image, 1.0, (1, 1),(123.68, 116.78, 103.94), swapRB=True, crop=False)

net = cv2.dnn.readNet("C:/Users/KHAN/frozen_east_text_detection.pb")

net.setInput(blob)

print(blob)

[[[[-11.68    ]]

  [[ 10.220001]]

  [[ 16.059998]]]]


In [1]:
import tensorflow as tf


In [4]:
import cv2 
cap=cv2.VideoCapture(0)
track=cv2.TrackerMOSSE_create()


In [1]:
import cv2 
cap=cv2.VideoCapture("F:/Clock.mp4")
track=cv2.TrackerMOSSE_create()
frame,img=cap.read()
bbox=cv2.selectROI('Tracking',img,False)
track.init(img,bbox)
def draw_box(img,bbox):
    x,y,w,h=int(bbox[0]),int(bbox[1]),int(bbox[2]),int(bbox[3])
    #cv2.rectangle(img,(x,y),((x+w),(y+h)),(255,0,0),3,1)
    cv2.line(img, (x, y), (x+w, y+h), (0, 255, 0), 2)
    cv2.putText(img,"Tracking",(75,45),cv2.FONT_HERSHEY_COMPLEX,0.7,(255,0,255),2)
    

while True:
    timer=cv2.getTickCount()
    frame,img=cap.read()
    
    frame,bbox=track.update(img)
    
    if frame:
        draw_box(img,bbox)
    else:
        cv2.putText(img,"Lost",(75,45),cv2.FONT_HERSHEY_COMPLEX,0.7,(0,255,255),2)
        
    

    fps=cv2.getTickFrequency()/(cv2.getTickCount()-timer)

    cv2.putText(img,str(int(fps)),(75,75),cv2.FONT_HERSHEY_COMPLEX,0.7,(0,255,0),2)
    
    
    cv2.imshow("Track_it",img)
    if cv2.waitKey(1)& 0xff==ord('q'):
        break
cv2.destroyAllWindows()

In [4]:
import cv2
import cv2 as cv

cap = cv2.VideoCapture("F:/clock2.mp4")

boxes = []

In [5]:
def on_mouse(event, x, y, flags, params):
    if event == cv.EVENT_LBUTTONDOWN:
        
        print ('Start Mouse Position: '+str(x)+', '+str(y))
        sbox = [x, y]
        boxes.append(sbox)
    elif event == cv.EVENT_LBUTTONUP:
        print ('End Mouse Position: '+str(x)+', '+str(y))
        ebox = [x, y]
        boxes.append(ebox)

count = 0
while(1):
    count += 1
    _,img = cap.read()
    img = cv2.blur(img, (3,3))

    cv2.namedWindow('real image')
    cv.setMouseCallback('real image', on_mouse, 0)
    cv2.imshow('real image', img)

    if count < 50:
        if cv2.waitKey(33) == 27:
            cv2.destroyAllWindows()
            break
    elif count >= 50:
        if cv2.waitKey(0) == 27:
            cv2.destroyAllWindows()
            break
        count = 0


Start Mouse Position: 254, 210
End Mouse Position: 254, 210
Start Mouse Position: 240, 263
End Mouse Position: 204, 325
Start Mouse Position: 157, 218
End Mouse Position: 204, 273
Start Mouse Position: 252, 155
End Mouse Position: 252, 155
Start Mouse Position: 310, 261
End Mouse Position: 160, 439
Start Mouse Position: 160, 439
End Mouse Position: 234, 243
Start Mouse Position: 161, 191
End Mouse Position: 279, 250


KeyboardInterrupt: 

In [1]:
import cv2 
import cv2 as cv
class DrawLineWidget():
        original_image = cv2.imread()
        clone = original_image.copy()

        cv2.namedWindow('image')
        cv2.setMouseCallback('image',extract_coordinates)

        # List to store start/end points
        image_coordinates = []

NameError: name 'extract_coordinates' is not defined

In [1]:
import cv2

class DrawLineWidget(object):
    def __init__(self):
        self.original_image = cv2.imread('F:/yes1.jpg')
        self.clone = self.original_image.copy()

        cv2.namedWindow('image')
        cv2.setMouseCallback('image', self.extract_coordinates)

        # List to store start/end points
        self.image_coordinates = []

    def extract_coordinates(self, event, x, y, flags, parameters):
        # Record starting (x,y) coordinates on left mouse button click
        if event == cv2.EVENT_LBUTTONDOWN:
            self.image_coordinates = [(x,y)]

        # Record ending (x,y) coordintes on left mouse bottom release
        elif event == cv2.EVENT_LBUTTONUP:
            self.image_coordinates.append((x,y))
            print('Starting: {}, Ending: {}'.format(self.image_coordinates[0], self.image_coordinates[1]))

            # Draw line
            cv2.line(self.clone, self.image_coordinates[0], self.image_coordinates[1], (36,255,12), 2)
            cv2.imshow("image", self.clone) 

        # Clear drawing boxes on right mouse button click
        elif event == cv2.EVENT_RBUTTONDOWN:
            self.clone = self.original_image.copy()

    def show_image(self):
        return self.clone

if __name__ == '__main__':
    draw_line_widget = DrawLineWidget()
    while True:
        cv2.imshow('image', draw_line_widget.show_image())
        #key = cv2.waitKey(1)

        # Close program with keyboard 'q'
        #if key == ord('q'):
        if cv2.waitKey(1)& 0xff==ord('q'):
            #cv2.destroyAllWindows()
            break
    cv2.destroyAllWindows()
            #exit(1)

Starting: (628, 373), Ending: (437, 471)


In [1]:
import cv2
image_coordinates = []
original_image = cv2.imread('F:/yes1.jpg')
clone = original_image.copy()
if event == cv2.EVENT_LBUTTONDOWN:
    
    
    image_coordinates = [(x,y)]

        # Record ending (x,y) coordintes on left mouse bottom release
elif event == cv2.EVENT_LBUTTONUP:
    
    image_coordinates.append((x,y))
    print('Starting: {}, Ending: {}'.format(self.image_coordinates[0], self.image_coordinates[1]))

            # Draw line
    cv2.line(clone, image_coordinates[0], image_coordinates[1], (36,255,12), 2)
    cv2.imshow("image", clone) 
elif event == cv2.EVENT_RBUTTONDOWN:
    clone = original_image.copy()

NameError: name 'event' is not defined

In [1]:
import cv2

def DrawLineWidget(obje):
    
        
    original_image = cv2.imread('F:/yes1.jpg')
    clone = self.original_image.copy()

    cv2.namedWindow('image')
    cv2.setMouseCallback('image', self.extract_coordinates)

    # List to store start/end points
    self.image_coordinates = []

def extract_coordinates(event, x, y, flags, parameters):
        # Record starting (x,y) coordinates on left mouse button click
    if event == cv2.EVENT_LBUTTONDOWN:
        image_coordinates = [(x,y)]

        # Record ending (x,y) coordintes on left mouse bottom release
    elif event == cv2.EVENT_LBUTTONUP:
        image_coordinates.append((x,y))
        print('Starting: {}, Ending: {}'.format(self.image_coordinates[0], self.image_coordinates[1]))

            # Draw line
        cv2.line(clone, image_coordinates[0], image_coordinates[1], (36,255,12), 2)
        cv2.imshow("image", self.clone) 

        # Clear drawing boxes on right mouse button click
    elif event == cv2.EVENT_RBUTTONDOWN:
        
        clone = original_image.copy()

def show_image():
    return clone

if __name__ == '__main__':
    draw_line_widget = DrawLineWidget()
    while True:
        cv2.imshow('image', draw_line_widget.show_image())
        #key = cv2.waitKey(1)

        # Close program with keyboard 'q'
        if key == ord('q'):
            
            break
        cv2.destroyAllWindows()
        #exit(1)

TypeError: DrawLineWidget() missing 1 required positional argument: 'obje'

In [5]:
import cv2 
import cv2 as cv
def DrawLineWidget(a):
    
        
    original_image = cv2.imread(a)
    clone = original_image.copy()

    cv2.namedWindow('image')
    cv2.setMouseCallback('image', extract_coordinates)

    # List to store start/end points
    image_coordinates = []

def extract_coordinates(event, x, y, flags, parameters):
        # Record starting (x,y) coordinates on left mouse button click
    if event == cv2.EVENT_LBUTTONDOWN:
        image_coordinates = [(x,y)]

        # Record ending (x,y) coordintes on left mouse bottom release
    elif event == cv2.EVENT_LBUTTONUP:
        image_coordinates.append((x,y))
        print('Starting: {}, Ending: {}'.format(image_coordinates[0], image_coordinates[1]))

            # Draw line
        cv2.line(clone, image_coordinates[0], image_coordinates[1], (36,255,12), 2)
        cv2.imshow("image", clone) 

        # Clear drawing boxes on right mouse button click
    elif event == cv2.EVENT_RBUTTONDOWN:
        
        clone = original_image.copy()

def show_image():
    return clone
draw_line_widget = DrawLineWidget('F:/yes1.jpg')
cv2.imshow('image', draw_line_widget)
cv2.destroyAllWindows()
while True:
    cv2.imshow('image', draw_line_widget)
    key = cv2.waitKey(1)

        # Close program with keyboard 'q'
    if cv2.waitKey(1)& 0xff==ord('q'):
        break
cv2.destroyAllWindows()

error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-71670poj\opencv\modules\highgui\src\window.cpp:376: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'cv::imshow'


# CORRECTED CODE

In [1]:
import cv2

class DrawLineWidget(object):
    def __init__(self):
        self.original_image = cv2.imread('F:/yes1.jpg')
        self.clone = self.original_image.copy()

        cv2.namedWindow('image')
        cv2.setMouseCallback('image', self.extract_coordinates)

        # List to store start/end points
        self.image_coordinates = []

    def extract_coordinates(self, event, x, y, flags, parameters):
        # Record starting (x,y) coordinates on left mouse button click
        if event == cv2.EVENT_LBUTTONDOWN:
            self.image_coordinates = [(x,y)]

        # Record ending (x,y) coordintes on left mouse bottom release
        elif event == cv2.EVENT_LBUTTONUP:
            self.image_coordinates.append((x,y))
            print('Starting: {}, Ending: {}'.format(self.image_coordinates[0], self.image_coordinates[1]))

            # Draw line
            cv2.line(self.clone, self.image_coordinates[0], self.image_coordinates[1], (36,255,12), 2)
            cv2.imshow("image", self.clone) 

        # Clear drawing boxes on right mouse button click
        elif event == cv2.EVENT_RBUTTONDOWN:
            self.clone = self.original_image.copy()

    def show_image(self):
        return self.clone

if __name__ == '__main__':
    draw_line_widget = DrawLineWidget()
    while True:
        cv2.imshow('image', draw_line_widget.show_image())
        #key = cv2.waitKey(1)

        # Close program with keyboard 'q'
        #if key == ord('q'):
        if cv2.waitKey(1)& 0xff==ord('q'):
            #cv2.destroyAllWindows()
            break
    cv2.destroyAllWindows()
            #exit(1)

Starting: (757, 344), Ending: (523, 457)


In [8]:
import cv2

class DrawLineWidget(object):
    def __init__(self,a):
        self.original_image = cv2.imread(a)
        self.clone = self.original_image.copy()

        cv2.namedWindow('image')
        cv2.setMouseCallback('image', self.extract_coordinates)

        # List to store start/end points
        self.image_coordinates = []

    def extract_coordinates(self, event, x, y, flags, parameters):
        # Record starting (x,y) coordinates on left mouse button click
        if event == cv2.EVENT_LBUTTONDOWN:
            self.image_coordinates = [(x,y)]

        # Record ending (x,y) coordintes on left mouse bottom release
        elif event == cv2.EVENT_LBUTTONUP:
            self.image_coordinates.append((x,y))
            print('Starting: {}, Ending: {}'.format(self.image_coordinates[0], self.image_coordinates[1]))

            # Draw line
            cv2.line(self.clone, self.image_coordinates[0], self.image_coordinates[1], (36,255,12), 2)
            cv2.imshow("image", self.clone) 

        # Clear drawing boxes on right mouse button click
        elif event == cv2.EVENT_RBUTTONDOWN:
            self.clone = self.original_image.copy()

    def show_image(self):
        return self.clone

if __name__ == '__main__':
    draw_line_widget = DrawLineWidget("F:/yes1.jpg")
    while True:
        cv2.imshow('image', draw_line_widget.show_image())
        if cv2.waitKey(1)& 0xff==ord('q'):
        
            break
    cv2.destroyAllWindows()
    

Starting: (835, 236), Ending: (669, 371)


In [8]:
import cv2 
cap=cv2.VideoCapture("F:/Clock.mp4")
track=cv2.TrackerMOSSE_create()
frame,img=cap.read()
bbox=cv2.selectROI('Tracking',img,False)
image_coordinates = []
imges=tuple(image_coordinates[0])
track.init(img,imges)
def draw_box(img,imges):
    image_coordinates = []
    imges=tuple(image_coordinates[])
    def extract_coordinates(event, x, y, flags, parameters):
        # Record starting (x,y) coordinates on left mouse button click
        if event == cv2.EVENT_LBUTTONDOWN:
            image_coordinates = [(x,y)]

        # Record ending (x,y) coordintes on left mouse bottom release
        elif event == cv2.EVENT_LBUTTONUP:
            image_coordinates.append((x,y))
            print('Starting: {}, Ending: {}'.format(image_coordinates[0],image_coordinates[1]))

            # Draw line
            cv2.line(img, image_coordinates[0], image_coordinates[1], (36,255,12), 2)
            #cv2.imshow("image", img) 

        # Clear drawing boxes on right mouse button click
        elif event == cv2.EVENT_RBUTTONDOWN:
            img = original_image.copy()
    #x,y,w,h=int(bbox[0]),int(bbox[1]),int(bbox[2]),int(bbox[3])
    #cv2.rectangle(img,(x,y),((x+w),(y+h)),(255,0,0),3,1)
    #cv2.line(img, (x, x+w), (y, y+h), (0, 255, 0), 2)
    cv2.putText(img,"Tracking",(75,45),cv2.FONT_HERSHEY_COMPLEX,0.7,(255,0,255),2)
while True:
    timer=cv2.getTickCount()
    frame,img=cap.read()
    
    frame,bbox=track.update(img)
    
    if frame:
        draw_box(img,imges)
    else:
        cv2.putText(img,"Lost",(75,45),cv2.FONT_HERSHEY_COMPLEX,0.7,(0,255,255),2)
        
    

    fps=cv2.getTickFrequency()/(cv2.getTickCount()-timer)

    cv2.putText(img,str(int(fps)),(75,75),cv2.FONT_HERSHEY_COMPLEX,0.7,(0,255,0),2)
    
    
    cv2.imshow("Track_it",img)
    if cv2.waitKey(1)& 0xff==ord('q'):
        break
cv2.destroyAllWindows()

SyntaxError: invalid syntax (<ipython-input-8-c540cb288994>, line 11)

In [2]:
import cv2 
#cap=cv2.VideoCapture("F:/clock7.wmv")
import math
import numpy as np
#track=cv2.TrackerMOSSE_create()
#track=cv2.TrackerBoosting_create()
#track=cv2.TrackerMIL_create()
#track=cv2.TrackerTLD_create()
track=cv2.TrackerKCF_create() # Better results
#track=cv2.TrackerMedianFlow_create()
frame,img=cap.read()
bbox=cv2.selectROI('Tracking',img,False)
print(bbox)

(651, 173, 71, 156)


# Tracking APIs in OpenCv

In [5]:
import cv2 
cap=cv2.VideoCapture("F:/clock7.wmv")
import math
import numpy as np
#track=cv2.TrackerMOSSE_create()
#track=cv2.TrackerBoosting_create()
#track=cv2.TrackerMIL_create()
#track=cv2.TrackerTLD_create()
track=cv2.TrackerKCF_create() # Better results
#track=cv2.TrackerMedianFlow_create()
frame,img=cap.read()
bbox=cv2.selectROI('Tracking',img,False)
center = (bbox[0]+(bbox[2]/2), bbox[1]+(bbox[3]/2))
print(center)
#area=bbox[3]*bbox[]
track.init(img,bbox)
def draw_box(img,mask):
    x,y,w,h=int(bbox[0]),int(bbox[1]),int(bbox[2]),int(bbox[3])
    #cv2.rectangle(img,(x,y),((x+w),(y+h)),(255,0,0),3,1)
    #cv2.line(img, (x, y), (x+w, y+h), (0, 255, 255), 2)
    cv2.circle(img,(int(center[0]),int(center[1])) , 5, (0,255,255), -1)
    cv2.putText(img,"Tracking",(75,45),cv2.FONT_HERSHEY_COMPLEX,0.7,(255,0,255),2)
    

while True:
    timer=cv2.getTickCount()
    frame,img=cap.read()
    #print(img)
    frame,bbox=track.update(img)
    track_window=bbox
    center = (bbox[0]+(bbox[2]/2), bbox[1]+(bbox[3]/2))
    cv2.circle(img, (int(center[0]),int(center[1])), 5, (0,255,255), -1)
    cv2.circle(img, (630,370), 5, (255,0,255), -1)
    diffx=abs(track_window[0]-630)
    diffy=abs(track_window[1]-370)
    per=math.atan2(diffy,diffx)
    p=math.degrees(per)

    #print(mask[0][0])
    #cv2.circle(img, (int(track_window[2]),int(track_window[3])), 9, (255,255,0), -1)
    #cv2.circle(mask,(30,30), 8, (255,0,255), -1)
    
    if frame:
        draw_box(img,bbox)
    else:
        cv2.putText(img,"Lost",(75,45),cv2.FONT_HERSHEY_COMPLEX,0.7,(0,255,255),2)
        
    

    fps=cv2.getTickFrequency()/(cv2.getTickCount()-timer)

    cv2.putText(img,str(p),(75,75),cv2.FONT_HERSHEY_COMPLEX,0.7,(0,255,0),2)
    
    
    cv2.imshow("Track_it",img)
    if cv2.waitKey(1)& 0xff==ord('q'):
        break
cv2.destroyAllWindows()

(689.5, 262.5)


# Second Approach
#CamShift

In [38]:
def mousePoints(event,x,y,flags,params):
    if event == cv2.EVENT_LBUTTONDOWN:
        size = len(pointsList)
        if size != 0 and size % 3 != 0:
            cv2.line(img,tuple(pointsList[round((size-1)/3)*3]),(x,y),(0,0,255),2)
        cv2.circle(img,(x,y),5,(0,0,255),cv2.FILLED)
        pointsList.append([x,y])
 
 
def gradient(pt1,pt2):
    return (pt2[1]-pt1[1])/(pt2[0]-pt1[0])
 
def getAngle(pointsList):
    pt1, pt2, pt3 = pointsList[-3:]
    m1 = gradient(pt1,pt2)
    m2 = gradient(pt1,pt3)
    angR = math.atan((m2-m1)/(1+(m2*m1)))
    angD = round(math.degrees(angR))
 
    cv2.putText(img,str(angD),(pt1[0]-40,pt1[1]-20),cv2.FONT_HERSHEY_COMPLEX,
                1.5,(0,0,255),2)

import cv2 
import cv2 as cv
import numpy as np
cap=cv2.VideoCapture("F:/clock7.wmv")
# take first frame of the video
ret,frame = cap.read()
frame=cv2.flip(frame,1)
_, f_new = cap.read()
f_new = cv2.flip(f_new, 1)
pointsList = []
# setup initial location of window
bbox=cv2.selectROI('Tracking',frame,False)
x, y, w, h = int(bbox[0]),int(bbox[1]),int(bbox[2]),int(bbox[3])# simply hardcoded the values
track_window = (x, y, w, h)
# set up the ROI for tracking
roi = frame[y:y+h, x:x+w]
hsv_roi =  cv.cvtColor(roi, cv.COLOR_BGR2HSV)
mask = cv.inRange(hsv_roi, np.array((0., 60.,32.)), np.array((180.,255.,255.)))
roi_hist = cv.calcHist([hsv_roi],[0],mask,[180],[0,180])
cv.normalize(roi_hist,roi_hist,0,255,cv.NORM_MINMAX)
# Setup the termination criteria, either 10 iteration or move by atleast 1 pt
term_crit = ( cv.TERM_CRITERIA_EPS | cv.TERM_CRITERIA_COUNT, 10, 1 )
while(1):
    ret, frame = cap.read()
    if ret == True:
        a1,a2=(650,50)
        diff = cv2.absdiff(frame, f_new)
        cv2.circle(frame, (a1,a2), 5, (0,0,255), -1)
        hsv = cv.cvtColor(frame, cv.COLOR_BGR2HSV)
        dst = cv.calcBackProject([hsv],[0],roi_hist,[0,180],1)
        # apply camshift to get the new location
        ret, track_window = cv.CamShift(dst, track_window, term_crit)
        
        
                
            
        pts = cv.boxPoints(ret)
        pts = np.int0(pts)
        cv2.line(frame, (a1,a2), (pts[0][0],pts[1][1]), (255,0,0), 4)
        cv2.circle(frame, (pts[0][0],pts[1][1]), 5, (0,0,255), -1)
        #print(pts)
        cv2.putText(frame,"{}".format(int(np.sqrt((pts[0][0] - 20)**2 + (pts[1][1] - 200)**2))),(155,145),cv2.FONT_HERSHEY_COMPLEX,0.7,(0,0,255),2)
        img2 = cv.polylines(frame,[pts],True, 255,2)
        cv.imshow('img2',img2)
        cv2.setMouseCallback('Image',mousePoints)
        if cv2.waitKey(1)& 0xff==ord('q'):
            break
cv2.destroyAllWindows()

#Mean Shift

In [30]:

import cv2 
import cv2 as cv
import numpy as np
cap=cv2.VideoCapture("F:/clock7.wmv")
# take first frame of the video
ret,frame = cap.read()
# setup initial location of window
bbox=cv2.selectROI('Tracking',frame,False)
x, y, w, h = int(bbox[0]),int(bbox[1]),int(bbox[2]),int(bbox[3])
# take first frame of the video
# setup initial location of window 
track_window = (x, y, w, h)
# set up the ROI for tracking
roi = frame[y:y+h, x:x+w]
hsv_roi =  cv.cvtColor(roi, cv.COLOR_BGR2HSV)
mask = cv.inRange(hsv_roi, np.array((0., 60.,32.)), np.array((180.,255.,255.)))
roi_hist = cv.calcHist([hsv_roi],[0],mask,[180],[0,180])
cv.normalize(roi_hist,roi_hist,0,255,cv.NORM_MINMAX)
# Setup the termination criteria, either 10 iteration or move by atleast 1 pt
term_crit = ( cv.TERM_CRITERIA_EPS | cv.TERM_CRITERIA_COUNT, 10, 1 )
while(1):
    ret, frame = cap.read()
    if ret == True:
        hsv = cv.cvtColor(frame, cv.COLOR_BGR2HSV)
        dst = cv.calcBackProject([hsv],[0],roi_hist,[0,180],1)
        # apply meanshift to get the new location
        ret, track_window = cv.meanShift(dst, track_window, term_crit)
        # Draw it on image
        x,y,w,h = track_window
        img2 = cv.rectangle(frame, (x,y), (x+w,y+h), 255,2)
        cv.imshow('img2',img2)
        k = cv.waitKey(30) & 0xff
        if k == 27:
            break
cv2.destroyAllWindows()
    

# Angle Calculater

In [1]:
import cv2
import math
import cv2 as cv
 
path = 'F:/clock.png'
img = cv2.imread(path)

pointsList = []
 
def mousePoints(event,x,y,flags,params):
    if event == cv2.EVENT_LBUTTONDOWN:
        size = len(pointsList)
        if size != 0 and size % 3 != 0:
            cv2.line(img,tuple(pointsList[round((size-1)/3)*3]),(x,y),(0,0,255),2)
        cv2.circle(img,(x,y),5,(0,0,255),cv2.FILLED)
        pointsList.append([x,y])
    
 
 
def gradient(pt1,pt2):
    return (pt2[1]-pt1[1])/(pt2[0]-pt1[0])
 
def getAngle(pointsList):
    pt1, pt2, pt3 = pointsList[-3:]
    m1 = gradient(pt1,pt2)
    m2 = gradient(pt1,pt3)
    angR = math.atan((m2-m1)/(1+(m2*m1)))
    angD = round(math.degrees(angR))
 
    cv2.putText(img,str(angD),(pt1[0]-40,pt1[1]-20),cv2.FONT_HERSHEY_COMPLEX,
                1.5,(0,0,255),2)
while True: 
    if len(pointsList) % 3 == 0 and len(pointsList) !=0:
        getAngle(pointsList)
        
    cv2.imshow('Image',img)
    cv2.setMouseCallback('Image',mousePoints)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        pointsList = []
        
        img = cv2.imread(path)
    k = cv.waitKey(30) & 0xff
    if k == 27:
        break
cv2.destroyAllWindows()

# Angle Calculator Practice

In [10]:
import cv2
import cv2 as cv
import math
 
path = 'F:/clock.png'
cap=cv2.VideoCapture("F:/clock7.wmv")
# take first frame of the video
ret,frame = cap.read()
img=frame.copy()
pointsList = []
 
def mousePoints(event,x,y,flags,params):
    if event == cv2.EVENT_LBUTTONDOWN:
        size = len(pointsList)
        if size != 0 and size % 3 != 0:
            cv2.line(img,tuple(pointsList[round((size-1)/3)*3]),(x,y),(0,0,255),2)
        cv2.circle(img,(x,y),5,(0,0,255),cv2.FILLED)
        pointsList.append([x,y])
 
 
def gradient(pt1,pt2):
    return (pt2[1]-pt1[1])/(pt2[0]-pt1[0])
 
def getAngle(pointsList):
    pt1, pt2, pt3 = pointsList[-3:]
    m1 = gradient(pt1,pt2)
    m2 = gradient(pt1,pt3)
    angR = math.atan((m2-m1)/(1+(m2*m1)))
    angD = round(math.degrees(angR))
 
    cv2.putText(img,str(angD),(pt1[0]-40,pt1[1]-20),cv2.FONT_HERSHEY_COMPLEX,
                1.5,(0,0,255),2)
while True: 
    ret,frame = cap.read()
    img=frame.copy()
    if len(pointsList) % 3 == 0 and len(pointsList) !=0:
        getAngle(pointsList)
 
    cv2.imshow('Image',img)
    cv2.setMouseCallback('Image',mousePoints)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        pointsList = []
        #img = cv2.imread(path)
    k = cv.waitKey(30) & 0xff
    if k == 27:
        break
cv2.destroyAllWindows()

# CAMSHIFT

In [4]:
import cv2 
import cv2 as cv
import numpy as np
cap=cv2.VideoCapture("F:/clock7.wmv")
# take first frame of the video
ret,frame = cap.read()
# setup initial location of window
bbox=cv2.selectROI('Tracking',frame,False)
x, y, w, h = int(bbox[0]),int(bbox[1]),int(bbox[2]),int(bbox[3])# simply hardcoded the values
track_window = (x, y, w, h)
# set up the ROI for tracking
roi = frame[y:y+h, x:x+w]
hsv_roi =  cv.cvtColor(roi, cv.COLOR_BGR2HSV)
mask = cv.inRange(hsv_roi, np.array((0., 60.,32.)), np.array((180.,255.,255.)))
roi_hist = cv.calcHist([hsv_roi],[0],mask,[180],[0,180])
cv.normalize(roi_hist,roi_hist,0,255,cv.NORM_MINMAX)
# Setup the termination criteria, either 10 iteration or move by atleast 1 pt
term_crit = ( cv.TERM_CRITERIA_EPS | cv.TERM_CRITERIA_COUNT, 10, 1 )
while(1):
    ret, frame = cap.read()
    if ret == True:
        hsv = cv.cvtColor(frame, cv.COLOR_BGR2HSV)
        dst = cv.calcBackProject([hsv],[0],roi_hist,[0,180],1)
        # apply camshift to get the new location
        ret, track_window = cv.CamShift(dst, track_window, term_crit)
        
        
        # Draw it on image
        pts = cv.boxPoints(ret)
        print(pts)
        #cv2.circle(frame,(pts[0][1],pts[0][2]))
        pts = np.int0(pts)
        
        img2 = cv.polylines(frame,[pts],True, 255,2)
        cv2.circle(img2, (630,370), 9, (255,25,25), -1)
        #print(img2)
        
        cv.imshow('img2',img2)
        if cv2.waitKey(1)& 0xff==ord('q'):
            break
cv2.destroyAllWindows()

[[632.3047  355.69055]
 [697.7849  216.1288 ]
 [706.6953  220.30945]
 [641.2151  359.87122]]
[[631.5512  357.76456]
 [702.5035  204.10493]
 [711.4488  208.23544]
 [640.4965  361.89508]]
[[631.5512  357.76456]
 [702.5035  204.10493]
 [711.4488  208.23544]
 [640.4965  361.89508]]
[[631.5512  357.76456]
 [702.5035  204.10493]
 [711.4488  208.23544]
 [640.4965  361.89508]]
[[631.5512  357.76456]
 [702.5035  204.10493]
 [711.4488  208.23544]
 [640.4965  361.89508]]
[[631.5512  357.76456]
 [702.5035  204.10493]
 [711.4488  208.23544]
 [640.4965  361.89508]]
[[631.5512  357.76456]
 [702.5035  204.10493]
 [711.4488  208.23544]
 [640.4965  361.89508]]
[[631.5512  357.76456]
 [702.5035  204.10493]
 [711.4488  208.23544]
 [640.4965  361.89508]]
[[631.5512  357.76456]
 [702.5035  204.10493]
 [711.4488  208.23544]
 [640.4965  361.89508]]
[[631.5512  357.76456]
 [702.5035  204.10493]
 [711.4488  208.23544]
 [640.4965  361.89508]]
[[631.5512  357.76456]
 [702.5035  204.10493]
 [711.4488  208.23544]
 

 [635.9217  368.3435 ]]
[[626.8012  361.6134 ]
 [725.86127 201.97198]
 [736.1988  208.3866 ]
 [637.13873 368.028  ]]
[[582.43494 408.94064]
 [675.6251  283.0402 ]
 [694.56506 297.05936]
 [601.3749  422.9598 ]]
[[598.07056 382.20685]
 [671.74646 296.8283 ]
 [687.92944 310.79315]
 [614.25354 396.1717 ]]
[[640.4352  348.2796 ]
 [702.12146 265.1941 ]
 [709.5648  270.7204 ]
 [647.87854 353.8059 ]]
[[641.2829  348.07205]
 [701.2464  267.37662]
 [708.7171  272.92795]
 [648.7536  353.62338]]
[[645.3763  343.0291 ]
 [697.9018  273.16534]
 [705.6237  278.9709 ]
 [653.0982  348.83466]]
[[646.10297 340.95575]
 [692.10175 280.14746]
 [699.89703 286.04425]
 [653.89825 346.85254]]
[[648.0486  338.92508]
 [690.0834  283.14566]
 [697.9514  289.07492]
 [655.9166  344.85434]]
[[648.0406  338.95712]
 [690.0926  283.11838]
 [697.9594  289.04288]
 [655.9074  344.88162]]
[[648.0406  338.95712]
 [690.0926  283.11838]
 [697.9594  289.04288]
 [655.9074  344.88162]]
[[648.0406  338.95712]
 [690.0926  283.11838]


[[656.7541  347.3068 ]
 [782.2569  259.55777]
 [787.2459  266.6932 ]
 [661.7431  354.44223]]
[[656.7541  347.3068 ]
 [782.2569  259.55777]
 [787.2459  266.6932 ]
 [661.7431  354.44223]]
[[656.7541  347.3068 ]
 [782.2569  259.55777]
 [787.2459  266.6932 ]
 [661.7431  354.44223]]
[[656.7541  347.3068 ]
 [782.2569  259.55777]
 [787.2459  266.6932 ]
 [661.7431  354.44223]]
[[656.7123  347.35074]
 [782.3069  259.52634]
 [787.2877  266.64926]
 [661.6931  354.47366]]
[[606.7527  372.70322]
 [697.7102  320.4393 ]
 [706.2473  335.29678]
 [615.2898  387.5607 ]]
[[652.3641  352.7862 ]
 [668.9433  337.73834]
 [676.6359  346.2138 ]
 [660.0567  361.26166]]
[[649.44183 352.61115]
 [681.8018  333.15277]
 [688.55817 344.38885]
 [656.1982  363.84723]]
[[648.31067 353.30377]
 [696.19507 325.30103]
 [701.68933 334.69623]
 [653.80493 362.69897]]
[[649.64874 354.11484]
 [714.9274  317.90903]
 [719.35126 325.88516]
 [654.0726  362.09097]]
[[648.91614 355.3133 ]
 [731.0138  311.12494]
 [735.08386 318.6867 ]
 

 [657.6009  370.3587 ]]
[[656.0152  361.5669 ]
 [807.36127 333.6358 ]
 [808.9848  342.4331 ]
 [657.63873 370.3642 ]]
[[652.3839  361.88736]
 [812.18164 334.68594]
 [813.6161  343.11264]
 [653.81836 370.31406]]
[[652.3839  361.88736]
 [812.18164 334.68594]
 [813.6161  343.11264]
 [653.81836 370.31406]]
[[652.31366 361.95596]
 [812.2581  334.67142]
 [813.68634 343.04404]
 [653.7419  370.32858]]
[[651.37305 361.9341 ]
 [811.1992  334.69034]
 [812.62695 343.0659 ]
 [652.8008  370.30966]]
[[651.333   361.9438 ]
 [811.23914 334.68146]
 [812.667   343.0562 ]
 [652.76086 370.31854]]
[[651.333   361.9438 ]
 [811.23914 334.68146]
 [812.667   343.0562 ]
 [652.76086 370.31854]]
[[651.333   361.9438 ]
 [811.23914 334.68146]
 [812.667   343.0562 ]
 [652.76086 370.31854]]
[[651.333   361.9438 ]
 [811.23914 334.68146]
 [812.667   343.0562 ]
 [652.76086 370.31854]]
[[651.333   361.9438 ]
 [811.23914 334.68146]
 [812.667   343.0562 ]
 [652.76086 370.31854]]
[[652.06903 361.98468]
 [812.50446 334.6443 ]


# CAMSHIFT PRACTICE

In [3]:
import cv2 
import cv2 as cv
import numpy as np
import math
cap=cv2.VideoCapture("F:/Clock3.wmv")

ret,frame = cap.read()
# setup initial location of window
bbox=cv2.selectROI('Tracking',frame,False)
x, y, w, h = int(bbox[0]),int(bbox[1]),int(bbox[2]),int(bbox[3])# simply hardcoded the values
track_window = (x, y, w, h)
# set up the ROI for tracking
roi = frame[y:y+h, x:x+w]
hsv_roi =  cv.cvtColor(roi, cv.COLOR_BGR2HSV)
mask = cv.inRange(hsv_roi, np.array((0., 60.,32.)), np.array((180.,255.,255.)))
roi_hist = cv.calcHist([hsv_roi],[0],mask,[180],[0,180])
cv.normalize(roi_hist,roi_hist,0,255,cv.NORM_MINMAX)
# Setup the termination criteria, either 10 iteration or move by atleast 1 pt
term_crit = ( cv.TERM_CRITERIA_EPS | cv.TERM_CRITERIA_COUNT, 10, 1 )
while(1):
    ret, frame = cap.read()
    if ret == True:
        hsv = cv.cvtColor(frame, cv.COLOR_BGR2HSV)
        dst = cv.calcBackProject([hsv],[0],roi_hist,[0,180],1)
        
        # apply camshift to get the new location
        ret, track_window = cv.CamShift(dst, track_window, term_crit)
        #cv2.circle(img, (int(track_window[2]),int(track_window[3])), 9, (255,255,0), -1)
        # Draw it on image
        center = (track_window[0]+(track_window[2]/2), track_window[1]+(track_window[3]/2))
        pts = cv.boxPoints(ret)
        
        #print(pts)
        #cv2.circle(frame,(pts[0][1],pts[0][2]))
        pts = np.int0(pts)
        cv2.circle(frame, (630,350), 7, (255,0,255), -1)
        diffx=abs(track_window[0]-630)
        diffy=abs(track_window[1]-370)
        per=math.atan2(diffy,diffx)
        p=math.degrees(per)
        cv2.putText(frame,str(int(p)),(75,45),cv2.FONT_HERSHEY_COMPLEX,0.7,(255,0,255),2)
        cv2.circle(frame, (int(center[0]),int(center[1])), 7, (255,0,255), -1)
        
        img2 = cv.polylines(frame,[pts],True, 255,2)
        
        #cv2.circle(img2, (), 7, (0,0,255), -1)
        
        cv.imshow('img2',img2)
        if cv2.waitKey(1)& 0xff==ord('q'):
            cv2.destroyAllWindows()
            break
        


In [10]:
import cv2
import numpy as np
import math

def distance(x1, y1, x2, y2):
    """
    Calculate distance between two points
    """
    dist = math.sqrt(math.fabs(x2-x1)**2 + math.fabs(y2-y1)**2)
    return dist

def find_color1(frame):
    """
    Filter "frame" for HSV bounds for color1 (inplace, modifies frame) & return coordinates of the object with that color
    """
    hsv_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    hsv_lowerbound = np.array([0., 60.,32.]) #replace THIS LINE w/ your hsv lowerb
    hsv_upperbound = np.array([180.,255.,255.])#replace THIS LINE w/ your hsv upperb
    mask = cv2.inRange(hsv_frame, hsv_lowerbound, hsv_upperbound)
    res = cv2.bitwise_and(frame, frame, mask=mask) #filter inplace
    cnts, hir = cv2.findContours(mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
    if len(cnts) > 0:
        maxcontour = max(cnts, key=cv2.contourArea

        #Find center of the contour 
        M = cv2.moments(maxcontour)
        if M['m00'] > 0 and cv2.contourArea(maxcontour) > 1000:
            cx = int(M['m10']/M['m00'])
            cy = int(M['m01']/M['m00'])
            return (cx, cy), True
        else:
            return (700, 700), False #faraway point
    else:
        return (700, 700), False #faraway point

def find_color2(frame):
    """
    Filter "frame" for HSV bounds for color1 (inplace, modifies frame) & return coordinates of the object with that color
    """
    hsv_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    hsv_lowerbound =  np.array([0., 60.,32.])#replace THIS LINE w/ your hsv lowerb
    hsv_upperbound = np.array([180.,255.,255.])#replace THIS LINE w/ your hsv upperb
    mask = cv2.inRange(hsv_frame, hsv_lowerbound, hsv_upperbound)
    res = cv2.bitwise_and(frame, frame, mask=mask)
    cnts, hir = cv2.findContours(mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
    if len(cnts) > 0:
        maxcontour = max(cnts, key=cv2.contourArea)

        #Find center of the contour 
        M = cv2.moments(maxcontour)
        if M['m00'] > 0 and cv2.contourArea(maxcontour) > 2000:
            cx = int(M['m10']/M['m00'])
            cy = int(M['m01']/M['m00'])
            return (cx, cy), True #True
        else:
            return (700, 700), True #faraway point
    else:
        return (700, 700), True #faraway point


cap = cv2.VideoCapture('F:/clock7.wmv')

while(1):
    _, orig_frame = cap.read()
    #we'll be inplace modifying frames, so save a copy
    copy_frame = orig_frame.copy() 
    (color1_x, color1_y), found_color1 = find_color1(copy_frame)
    (color2_x, color2_y), found_color2 = find_color2(copy_frame)

    #draw circles around these objects
    cv2.circle(copy_frame, (color1_x, color1_y), 20, (255, 0, 0), -1)
    cv2.circle(copy_frame, (color2_x, color2_y), 20, (0, 128, 255), -1)

    if found_color1 and found_color2:
        #trig stuff to get the line
        hypotenuse = distance(color1_x, color1_y, color2_x, color2_y)
        horizontal = distance(color1_x, color1_y, color2_x, color1_y)
        vertical = distance(color2_x, color2_y, color2_x, color1_y)
        angle = np.arcsin(vertical/hypotenuse)*180.0/math.pi

        #draw all 3 lines
        cv2.line(copy_frame, (color1_x, color1_y), (color2_x, color2_y), (0, 0, 255), 2)
        cv2.line(copy_frame, (color1_x, color1_y), (color2_x, color1_y), (0, 0, 255), 2)
        cv2.line(copy_frame, (color2_x, color2_y), (color2_x, color1_y), (0, 0, 255), 2)

        #put angle text (allow for calculations upto 180 degrees)
        angle_text = ""
        if color2_y < color1_y and color2_x > color1_x:
            angle_text = str(int(angle))
        elif color2_y < color1_y and color2_x < color1_x:
            angle_text = str(int(180 - angle))
        elif color2_y > color1_y and color2_x < color1_x:
            angle_text = str(int(180 + angle))
        elif color2_y > color1_y and color2_x > color1_x:
            angle_text = str(int(360 - angle))
        
        #CHANGE FONT HERE
        cv2.putText(copy_frame, angle_text, (color1_x-30, color1_y), cv2.FONT_HERSHEY_COMPLEX, 1, (0, 128, 229), 2)

    cv2.imshow('AngleCalc', copy_frame)
    if cv2.waitKey(1)& 0xff==ord('q'):
        break 

cap.release()

cv2.destroyAllWindows()

SyntaxError: invalid syntax (<ipython-input-10-d38e00ea6513>, line 26)

In [15]:
import cv2 
path = 'F:/clock.png'
#ret,frame = cap.read()
frame=cv2.imread(path)

hsv_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
hsv_lowerbound =  np.array([255, 255, 0])#replace THIS LINE w/ your hsv lowerb
hsv_upperbound = np.array([0, 255, 255])#replace THIS LINE w/ your hsv upperb
mask = cv2.inRange(hsv_frame, hsv_lowerbound, hsv_upperbound)
res = cv2.bitwise_and(frame, frame, mask=mask)
#cnts, hir = cv2.findContours(mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
cv2.imshow('AngleCalc', hsv_upperbound)
cv2.waitKey(0)
cv2.destroyAllWindows()


error: OpenCV(4.4.0) C:/Users/appveyor/AppData/Local/Temp/1/pip-req-build-71670poj/opencv/modules/highgui/src/precomp.hpp:137: error: (-215:Assertion failed) src_depth != CV_16F && src_depth != CV_32S in function 'convertToShow'


In [ ]:
import cv2
import numpy as np
 
 #image_path
img_path="F:/clock.png"
 
#read image
img_raw = cv2.imread(img_path)
 
#select ROIs function
ROIs = cv2.selectROIs("Select Rois",img_raw)
 
#print rectangle points of selected roi
print(ROIs)
 
#Crop selected roi ffrom raw image
 
#counter to save image with different name
crop_number=0 
 
#loop over every bounding box save in array "ROIs"
for rect in ROIs:
    
    x1=rect[0]
    y1=rect[1]
    x2=rect[2]
    y2=rect[3]

            #crop roi from original image
    img_crop=img_raw[y1:y1+y2,x1:x1+x2]

            #show cropped image
    cv2.imshow("crop"+str(crop_number),img_crop)

     #save cropped image
    #cv2.imwrite("crop"+str(crop_number)+".jpeg",img_crop)

    crop_number+=1

    #hold window
cv2.waitKey(0)
cv2.destroAllWindows()    

In [ ]:
_, prev = cap.read()
prev = cv2.flip(prev, 1)
_, new = cap.read()
new = cv2.flip(new, 1)
diff = cv2.absdiff(prev, new)

In [27]:
_, prev = cap.read()
prev = cv2.flip(prev, 1)
_, new = cap.read()
new = cv2.flip(new, 1)

error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-71670poj\opencv\modules\imgproc\src\shapedescr.cpp:315: error: (-215:Assertion failed) npoints >= 0 && (depth == CV_32F || depth == CV_32S) in function 'cv::contourArea'


# CORRECTED CODE

In [ ]:
def mousePoints(event,x,y,flags,params):
    if event == cv2.EVENT_LBUTTONDOWN:
        size = len(pointsList)
        if size != 0 and size % 3 != 0:
            cv2.line(img,tuple(pointsList[round((size-1)/3)*3]),(x,y),(0,0,255),2)
        cv2.circle(img,(x,y),5,(0,0,255),cv2.FILLED)
        pointsList.append([x,y])
 
 
def gradient(pt1,pt2):
    return (pt2[1]-pt1[1])/(pt2[0]-pt1[0])
 
def getAngle(pointsList):
    pt1, pt2, pt3 = pointsList[-3:]
    m1 = gradient(pt1,pt2)
    m2 = gradient(pt1,pt3)
    angR = math.atan((m2-m1)/(1+(m2*m1)))
    angD = round(math.degrees(angR))
 
    cv2.putText(img,str(angD),(pt1[0]-40,pt1[1]-20),cv2.FONT_HERSHEY_COMPLEX,
                1.5,(0,0,255),2)



import cv2 
import cv2 as cv
import numpy as np
import math
cap=cv2.VideoCapture("F:/clock7.wmv")
# take first frame of the video
ret,frame = cap.read()
frame=cv2.flip(frame,1)
_, f_new = cap.read()
f_new = cv2.flip(f_new, 1)
pointsList = []

bbox=cv2.selectROI('Tracking',frame,False)
x, y, w, h = int(bbox[0]),int(bbox[1]),int(bbox[2]),int(bbox[3])
track_window = (x, y, w, h)

roi = frame[y:y+h, x:x+w]
hsv_roi =  cv.cvtColor(roi, cv.COLOR_BGR2HSV)
mask = cv.inRange(hsv_roi, np.array((0., 60.,32.)), np.array((180.,255.,255.)))
roi_hist = cv.calcHist([hsv_roi],[0],mask,[180],[0,180])
cv.normalize(roi_hist,roi_hist,0,255,cv.NORM_MINMAX)
term_crit = ( cv.TERM_CRITERIA_EPS | cv.TERM_CRITERIA_COUNT, 10, 1 )
while(1):
    ret, frame = cap.read()
    if ret == True:
        a1,a2=(650,50)
        diff = cv2.absdiff(frame, f_new)
        cv2.circle(frame, (a1,a2), 5, (0,0,255), -1)
        hsv = cv.cvtColor(frame, cv.COLOR_BGR2HSV)
        dst = cv.calcBackProject([hsv],[0],roi_hist,[0,180],1)
        # apply camshift to get the new location
        ret, track_window = cv.CamShift(dst, track_window, term_crit)
        
        
                
            
        pts = cv.boxPoints(ret)
        pts = np.int0(pts)
        #cv2.line(frame, (a1,a2), (pts[0][0],pts[1][1]), (255,0,0), 4)
        cv2.circle(frame, (pts[0][0],pts[1][1]), 5, (0,0,255), -1)
        print(track_window)
        cv2.circle(frame, (track_window[0],track_window[1]), 5, (0,255,255), -1)
        cv2.circle(frame, (630,370), 5, (255,0,255), -1)
        diffx=track_window[0]-630
        diffy=track_window[1]-370
        per=math.atan2(diffy,diffx)
        print(per)
        cv2.putText(frame,str(per),(155,145),cv2.FONT_HERSHEY_COMPLEX,0.7,(0,0,255),2)
        img2 = cv.polylines(frame,[pts],True, 255,2)
        cv.imshow('img2',img2)
        cv2.setMouseCallback('Image',mousePoints)
        if cv2.waitKey(1)& 0xff==ord('q'):
            break
cv2.destroyAllWindows()

(634, 325, 14, 30)
-1.482140444927459
(643, 297, 23, 44)
-1.3945616290582208
(644, 278, 31, 64)
-1.4197809838735371
(643, 276, 32, 66)
-1.4333701812979533
(643, 276, 32, 66)
-1.4333701812979533
(643, 276, 32, 66)
-1.4333701812979533
(643, 276, 32, 66)
-1.4333701812979533
(643, 276, 32, 66)
-1.4333701812979533
(643, 276, 32, 66)
-1.4333701812979533
(643, 276, 32, 66)
-1.4333701812979533
(643, 276, 32, 66)
-1.4333701812979533
(643, 276, 32, 66)
-1.4333701812979533
(643, 276, 32, 66)
-1.4333701812979533
(643, 276, 32, 66)
-1.4333701812979533
(643, 276, 32, 66)
-1.4333701812979533
(643, 276, 32, 66)
-1.4333701812979533
(643, 276, 32, 66)
-1.4333701812979533
(643, 276, 32, 66)
-1.4333701812979533
(643, 276, 32, 66)
-1.4333701812979533
(643, 276, 32, 66)
-1.4333701812979533
(643, 276, 32, 66)
-1.4333701812979533
(643, 276, 32, 66)
-1.4333701812979533
(643, 276, 32, 66)
-1.4333701812979533
(643, 276, 32, 66)
-1.4333701812979533
(643, 276, 32, 66)
-1.4333701812979533
(643, 276, 32, 66)
-1.4333

(647, 340, 49, 25)
-1.0552473193359175
(650, 341, 43, 21)
-0.9670469933974603
(681, 319, 67, 29)
-0.7853981633974483
(677, 313, 85, 37)
-0.8812573105074615
(666, 315, 99, 40)
-0.9912323415015735
(661, 314, 106, 43)
-1.0652152719206915
(661, 313, 107, 44)
-1.0726796167945825
(661, 313, 107, 44)
-1.0726796167945825
(661, 313, 107, 44)
-1.0726796167945825
(661, 313, 107, 44)
-1.0726796167945825
(661, 313, 107, 44)
-1.0726796167945825
(661, 313, 107, 44)
-1.0726796167945825
(661, 313, 107, 44)
-1.0726796167945825
(661, 313, 107, 44)
-1.0726796167945825
(665, 304, 127, 52)
-1.083201200871883
(664, 304, 130, 53)
-1.0951011079399045
(664, 303, 131, 53)
-1.1011964071394988
(664, 303, 131, 53)
-1.1011964071394988
(664, 303, 131, 53)
-1.1011964071394988
(664, 303, 131, 53)
-1.1011964071394988
(664, 303, 131, 53)
-1.1011964071394988
(664, 303, 131, 53)
-1.1011964071394988
(664, 303, 131, 53)
-1.1011964071394988
(664, 303, 131, 53)
-1.1011964071394988
(654, 348, 35, 15)
-0.7419472680059175
(660, 3

(584, 338, 20, 17)
-2.5337906574758327
(583, 331, 29, 22)
-2.4489508103804885
(582, 331, 30, 22)
-2.459276098715045
(557, 332, 51, 16)
-2.661642141270325
(543, 324, 63, 27)
-2.655221683747346
(561, 332, 45, 20)
-2.638193269193139
(566, 332, 39, 20)
-2.6057814156293295
(566, 332, 39, 20)
-2.6057814156293295
(566, 332, 39, 20)
-2.6057814156293295
(566, 332, 39, 20)
-2.6057814156293295
(566, 332, 39, 20)
-2.6057814156293295
(566, 332, 39, 20)
-2.6057814156293295
(566, 332, 39, 20)
-2.6057814156293295
(563, 332, 40, 18)
-2.6256671401245084
(563, 332, 40, 18)
-2.6256671401245084
(563, 329, 50, 19)
-2.5924397509107826
(559, 324, 54, 26)
-2.566704052319701
(548, 311, 64, 42)
-2.517890937362902
(537, 302, 72, 48)
-2.510243724346016
(537, 302, 72, 48)
-2.510243724346016
(537, 302, 72, 48)
-2.510243724346016
(538, 302, 71, 48)
-2.505084437801842
(538, 302, 71, 48)
-2.505084437801842
(538, 302, 71, 48)
-2.505084437801842
(535, 301, 74, 47)
-2.513422541168914
(537, 293, 65, 51)
-2.4500357028216815

(613, 271, 6, 5)
-1.7408549483869529
(610, 270, 17, 5)
-1.7681918866447774
(611, 266, 19, 9)
-1.7514958500741893
(611, 266, 19, 9)
-1.7514958500741893
(613, 265, 16, 8)
-1.7313082522767558
(613, 265, 16, 8)
-1.7313082522767558
(613, 265, 16, 8)
-1.7313082522767558
(611, 265, 19, 11)
-1.7498116038163822
(611, 265, 19, 11)
-1.7498116038163822
(611, 265, 19, 11)
-1.7498116038163822
(611, 265, 19, 11)
-1.7498116038163822
(611, 265, 19, 11)
-1.7498116038163822
(611, 265, 19, 11)
-1.7498116038163822
(611, 265, 19, 11)
-1.7498116038163822
(603, 263, 30, 27)
-1.8179727885808665
(603, 263, 30, 27)
-1.8179727885808665
(603, 263, 30, 27)
-1.8179727885808665
(603, 263, 30, 27)
-1.8179727885808665
(603, 263, 30, 27)
-1.8179727885808665
(603, 263, 30, 27)
-1.8179727885808665
(603, 263, 30, 27)
-1.8179727885808665
(603, 263, 30, 27)
-1.8179727885808665
(603, 263, 30, 27)
-1.8179727885808665
(622, 268, 12, 4)
-1.6490674673161745
(636, 269, 8, 14)
-1.5114601210915253
(631, 269, 16, 22)
-1.5608956602069

(686, 292, 20, 19)
-0.9481255380378293
(687, 295, 6, 18)
-0.9209258773829491
(687, 295, 6, 18)
-0.9209258773829491
(671, 318, 16, 5)
-0.9031307382015419
(670, 318, 12, 6)
-0.9151007005533605
(679, 301, 20, 18)
-0.9532940866478229
(687, 304, 31, 11)
-0.8584387287005676
(689, 304, 31, 14)
-0.8413397346310093
(689, 304, 31, 14)
-0.8413397346310093
(682, 301, 40, 21)
-0.924980407321327
(658, 305, 64, 24)
-1.1640492550689256
(651, 303, 71, 33)
-1.2670618409523098
(651, 302, 71, 34)
-1.2712643377249735
(651, 302, 71, 34)
-1.2712643377249735
(651, 302, 71, 34)
-1.2712643377249735
(658, 304, 58, 28)
-1.169567527790048
(658, 304, 58, 28)
-1.169567527790048
(658, 304, 58, 28)
-1.169567527790048
(658, 304, 58, 28)
-1.169567527790048
(658, 304, 58, 28)
-1.169567527790048
(658, 304, 58, 28)
-1.169567527790048
(658, 304, 58, 28)
-1.169567527790048
(657, 306, 60, 27)
-1.171575557219644
(657, 306, 60, 27)
-1.171575557219644
(665, 302, 44, 31)
-1.0954533446284016
(650, 307, 78, 35)
-1.263398853672075
(

In [6]:
import numpy as np
import cv2 as cv
img = cv.imread("F:/clock.png",0)
ret,thresh = cv.threshold(img,127,255,0)
contours,hierarchy = cv.findContours(thresh, 1, 2)
cnt = contours[0]
M = cv.moments(cnt)
print( M )

{'m00': 106.5, 'm10': 76830.33333333333, 'm01': 61788.166666666664, 'm20': 55427456.25, 'm11': 44575286.625, 'm02': 35848697.416666664, 'm30': 39987688176.200005, 'm21': 32158227168.1, 'm12': 25862347368.9, 'm03': 20799544399.050003, 'mu20': 1164.0423839315772, 'mu11': 587.6479525342584, 'mu02': 1020.9844809547067, 'mu30': -152.7670669555664, 'mu21': -90.68429074971937, 'mu12': 31.176341562066227, 'mu03': 171.04578399658203, 'nu20': 0.10262887733311973, 'nu11': 0.05181052723527152, 'nu02': 0.09001604451980046, 'nu30': -0.001305135855536139, 'nu21': -0.0007747436783986146, 'nu12': 0.000266349037315281, 'nu03': 0.0014612965351829355}


In [16]:

import cv2
import numpy as np 

cap = cv2.VideoCapture(0)

_, prev = cap.read()
prev = cv2.flip(prev, 1)
_, new = cap.read()
new = cv2.flip(new, 1)


while True:
    diff = cv2.absdiff(prev, new)
    diff = cv2.cvtColor(diff, cv2.COLOR_BGR2GRAY)
    diff = cv2.blur(diff, (5,5))
    _,thresh = cv2.threshold(diff, 10, 255, cv2.THRESH_BINARY)
    threh = cv2.dilate(thresh, None, 3)
    thresh = cv2.erode(thresh, np.ones((4,4)), 1)
    _,contor, = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
    cv2.circle(prev, (20,200), 5, (0,0,255), -1)
    for contors in contor:
        
        a=cv2.contourArea(contors)
        if a > 30000:
            (x,y,w,h) = cv2.boundingRect(contors)
            (x1,y1),rad = cv2.minEnclosingCircle(contors)
            x1 = int(x1)
            y1 = int(y1)
            cv2.line(prev, (20,200), (x1, y1), (255,0,0), 4)
            cv2.putText(prev, "{}".format(int(np.sqrt((x1 - 20)**2 + (y1 - 200)**2))), (100,100),cv2.FONT_HERSHEY_SIMPLEX, 2, (0,255,0), 3)
            cv2.rectangle(prev, (x,y), (x+w,y+h), (0,255,0), 2)
            cv2.circle(prev, (x1,y1), 5, (0,0,255), -1)

    cv2.imshow("orig", prev)

    prev = new
    _, new = cap.read()
    new = cv2.flip(new, 1)

    if cv2.waitKey(1) == 27:
        break

cap.release()
cv2.destroyAllWindows()

error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-71670poj\opencv\modules\imgproc\src\shapedescr.cpp:315: error: (-215:Assertion failed) npoints >= 0 && (depth == CV_32F || depth == CV_32S) in function 'cv::contourArea'


In [19]:
import numpy as np
import cv2

img=cv2.imread('F:/clock.png')
hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
 #Help
lower = np.array([0,50,50])
upper = np.array([9,255,255])
    
mask = cv2.inRange(hsv, lower, upper)
mask1=mask.copy()
cv2.circle(mask1,(mask[1][0],mask[0][1]), 8, (255,0,255), -1)
    #cv2.rectangle(mask, (mask), (x+w,y+h), (0,255,0), 2)
print(mask)
cv2.imshow('screen', mask1)



cv2.waitKey(0)
cv2.destroyAllWindows()





    
    

TypeError: only size-1 arrays can be converted to Python scalars

In [1]:
import cv2 
import cv2 as cv
import numpy as np
cap=cv2.VideoCapture("F:/clock7.wmv")
# take first frame of the video
ret,frame = cap.read()
# setup initial location of window
bbox=cv2.selectROI('Tracking',frame,False)
x, y, w, h = int(bbox[0]),int(bbox[1]),int(bbox[2]),int(bbox[3])# simply hardcoded the values
track_window = (x, y, w, h)
# set up the ROI for tracking
roi = frame[y:y+h, x:x+w]
hsv_roi =  cv.cvtColor(roi, cv.COLOR_BGR2HSV)
mask = cv.inRange(hsv_roi, np.array((0., 60.,32.)), np.array((180.,255.,255.)))
roi_hist = cv.calcHist([hsv_roi],[0],mask,[180],[0,180])
cv.normalize(roi_hist,roi_hist,0,255,cv.NORM_MINMAX)
# Setup the termination criteria, either 10 iteration or move by atleast 1 pt
term_crit = ( cv.TERM_CRITERIA_EPS | cv.TERM_CRITERIA_COUNT, 10, 1 )
while(1):
    ret, frame = cap.read()
    if ret == True:
        hsv = cv.cvtColor(frame, cv.COLOR_BGR2HSV)
        dst = cv.calcBackProject([hsv],[0],roi_hist,[0,180],1)
        # apply camshift to get the new location
        ret, track_window = cv.CamShift(dst, track_window, term_crit)
        pts = cv.boxPoints(ret)
        #cv2.circle(frame, (int(ret[1][1]),int(ret[1][1])), 9, (255,255,0), -1)
        #cv2.rectangle(frame, (int(ret[1][0]),int(ret[0][1])), (int(ret[0][1]+20,int(ret[1][0])+30), (0,255,0), 2)
        # Draw it on image
        
        print(pts)
        #cv2.circle(frame,(pts[0][1],pts[0][0]))
        pts = np.int0(pts)
        img2 = cv.polylines(frame,[pts],True,255,2)
        img3=cv.circle(frame,[pts],9,(255,255,0),-1)
        
        x=int(pts[0][1])
        y=int(pts[1][0])
        #cv2.circle(frame, (int(pts[1][1]),int(pts[1][1])), 9, (255,255,0), -1)
        cv2.rectangle(frame, (x,y), (x+80,y+60), (0,255,0), -1)
        cv.imshow('img2',img2)
        if cv2.waitKey(1)& 0xff==ord('q'):
            break
cv2.destroyAllWindows()

[[631.65485 356.18527]
 [694.58795 221.71626]
 [703.34515 225.81473]
 [640.41205 360.28375]]


SystemError: new style getargs format but argument is not a tuple